# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nadeem Abdulla
#email: anadeem92@yahoo.co.in
description: > # this means to ignore newlines until "baseurl:"
  Hello.<br>I'm Nadeem Abdulla.<br>Welcome to my portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: nadeemabd
github_username:  nadeemabd

port: 4444

# Build settings
markdown: kramdown

gems:
  - octopress-autoprefixer
  - jekyll-minimagick

mini_magick:
    wide:
        source: /assets/images/og
        destination: /assets/images/wide
        resize: "480x300"
    square:
        source: /assets/images/og
        destination: /assets/images/square
        resize: "600x400"
    thumb:
        source: /assets/images/og
        destination: /assets/images/thumb
        resize: "600x400"
    feature:
        source: /assets/images/og
        destination: /assets/images/feature
        resize: "1920x1200"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      thumb-image-path: /assets/images/thumb/
      feature-image-path: /assets/images/feature/