# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nadeem Abdulla
email: anadeem92@yahoo.co.in
description: > # this means to ignore newlines until "baseurl:"
  Hello. I am Nadeem Abdulla. Welcome to my portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nadeemabd.github.io/" # the base hostname & protocol for your site
twitter_username: nadeemabd
github_username:  nadeemabd

# Build settings
markdown: kramdown
